package org.magicghostvu.jenet

object EnetConstant {
    const val ENET_HOST_RECEIVE_BUFFER_SIZE = 256 * 1024
    const val ENET_HOST_SEND_BUFFER_SIZE = 256 * 1024
    const val ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL = 1000
    const val ENET_HOST_DEFAULT_MTU = 1400
    const val ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE = 32 * 1024 * 1024
    const val ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA = 32 * 1024 * 1024

    const val ENET_PEER_DEFAULT_ROUND_TRIP_TIME = 500
    const val ENET_PEER_DEFAULT_PACKET_THROTTLE = 32
    const val ENET_PEER_PACKET_THROTTLE_SCALE = 32
    const val ENET_PEER_PACKET_THROTTLE_COUNTER = 7
    const val ENET_PEER_PACKET_THROTTLE_ACCELERATION = 2
    const val ENET_PEER_PACKET_THROTTLE_DECELERATION = 2
    const val ENET_PEER_PACKET_THROTTLE_INTERVAL = 5000
    const val ENET_PEER_PACKET_LOSS_SCALE = (1 shl 16)
    const val ENET_PEER_PACKET_LOSS_INTERVAL = 10000
    const val ENET_PEER_WINDOW_SIZE_SCALE = 64 * 1024
    const val ENET_PEER_TIMEOUT_LIMIT = 32
    const val ENET_PEER_TIMEOUT_MINIMUM = 5000
    const val ENET_PEER_TIMEOUT_MAXIMUM = 30000
    const val ENET_PEER_PING_INTERVAL = 500
    const val ENET_PEER_UNSEQUENCED_WINDOWS = 64
    const val ENET_PEER_UNSEQUENCED_WINDOW_SIZE = 1024
    const val ENET_PEER_FREE_UNSEQUENCED_WINDOWS = 32
    const val ENET_PEER_RELIABLE_WINDOWS = 16
    const val ENET_PEER_RELIABLE_WINDOW_SIZE = 0x1000
    const val ENET_PEER_FREE_RELIABLE_WINDOWS = 8
}