package org.magicghostvu.jenet

object ProtocolConstants {
    val ENET_PROTOCOL_MINIMUM_MTU = 576
    val ENET_PROTOCOL_MAXIMUM_MTU = 4096
    val ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS = 32
    val ENET_PROTOCOL_MINIMUM_WINDOW_SIZE: UInt = 4096.toUInt()
    val ENET_PROTOCOL_MAXIMUM_WINDOW_SIZE: UInt = 65536.toUInt()
    val ENET_PROTOCOL_MINIMUM_CHANNEL_COUNT = 1
    val ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT = 255
    val ENET_PROTOCOL_MAXIMUM_PEER_ID = 0xFFF
    val ENET_PROTOCOL_MAXIMUM_FRAGMENT_COUNT = 1024 * 1024


}